config/routes.rb
Rails.application.routes.draw do
  root 'html_pages#home'
  get '/help', to: 'html_pages#help'
  get '/about', to: 'html_pages#about'
  get '/contact', to: 'html_pages#contact'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	before_save { self.email = email.downcase }
	validates :name, presence: true, length: {maximum: 60}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 255}, 
					  format: { with: VALID_EMAIL_REGEX },
					  uniqueness: true
	has_secure_password
	validates :password, presence: true, length: {minimum: 6}
	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end
end

app/controllers/application_controller.rb
 class ApplicationController < ActionController::Base
	include SessionsHelper
end

app/controllers/html_pages_controller.rb
class HtmlPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  		log_in user
  		redirect_to user
  	else
  		flash.now[:danger] = "Invalid email/password combination"
  		render 'new'
  	end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end
  def show
  	@user = User.find(params[:id])
  end
  def create
  	#@user = User.new(params[:user])
  	@user = User.new(name: params[:user][:name], email: params[:user][:email], password: params[:user][:password], password_confirmation: params[:user][:password_confirmation])
  	if @user.save
      log_in @user
      flash[:success] = "Welcome to Orbit"
  		redirect_to @user
      #render 'show'
  	else
  		render 'new'
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title = '')
		base_title = 'Orbit Feedback Application'
		if page_title.empty?
			base_title
		else
			page_title + ' | ' + base_title
		end
	end
end

app/helpers/html_pages_helper.rb
module HtmlPagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
		if session[:user_id]
			@current_user ||= User.find_by(id: session[:user_id])
		end
	end

	def logged_in?
		!current_user.nil?
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/html_pages/about.html.erb
<%provide(:title, 'About') %>

<h1>Orbit About Page</h1>
<p>This is a template <b>about page</b> for our Orbit Feedback Application</p>

app/views/html_pages/contact.html.erb
<% provide(:title, 'Contact') %>

<h1>Contact Us</h1>

<p>Contact</p>

app/views/html_pages/help.html.erb
<%provide(:title, 'Help') %>

<h1>Orbit Help Page</h1>
<p>This is a template <b>help page</b> for our Orbit Feedback Application</p>

app/views/html_pages/home.html.erb
<%provide(:title, 'Home') %>

<div class="center jumbotron">
	<h1>Welcome to Orbit</h1>
	<h2>
		This is the homepage of the Orbit application. You can fnd the codebase for this application at
		<a href="https://github.com/tstaunton/orbit001">my Github account.</a>
	</h2>

	<%= link_to "Create an account", signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		Orbit Feedback Application
	</small>

	<nav>
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Orbit Application", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>  
        <li><%= link_to "Help", help_path %></li>   
        <% if logged_in? %>   
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li><%= link_to "Log Out", logout_path, method: :delete %></li>
            </ul>
          </li> 
        <% else %>
          <li><%= link_to "Login", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>      
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
          <%= message %>
        </div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">
			The form contains <%= pluralize(@user.errors.count, "error") %>
		</div>
		<ul>
			<% @user.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Signup') %>
<h1>Signup</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_with(model: @user, local: true) do |f| %>
			<%= render 'shared/error_messages' %>

			<%= f.label :name %>
			<%= f.text_field :name, class: "form-control" %>

			<%= f.label :email %>
			<%= f.email_field :email, class: "form-control" %>

			<%= f.label :password %>
			<%= f.password_field :password, class: "form-control" %>

			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation, class: "form-control" %>

			<%= f.submit "Create my Account", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<%= provide(:title, @user.name) %>
<div class="row">
	<aside>
		<section>
			<h1>
				<%= gravatar_for @user %>
				<%= @user.name %>
			</h1>
		</section>
	</aside>
</div>